# 마스터3 - 워커3개로 구성
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.30.2
  extraPortMappings:
  - containerPort: 30007    # 호스트 포트와 컨테이너 포트를 매핑. service에서 nodePort를 사용하려면 노드포트=컨테이너포트 여야 함
    hostPort: 30007
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # 이 부분도 nfs 패키지 설치하는데 아무 상관 없음.
  # extraMounts:
  # - hostPath: /var/run/docker.sock
  #   containerPath: /var/run/docker.sock
  # 이 설정도 nfs 패키지 설치하는데 아무 상관 없음. 필요한 것만 넣지 헷갈리게 왜 이런걸 마음대로 넣냐고 ㅎ

  # 역시 검토 필수..
  # kubeadmConfigPatches는 kubeadm의 구성을 변경하는 것으로, 이를 통해 노드 레이블을 추가할 수 있음
  # - initConfiguration: 마스터 노드가 초기화될 때 사용되는 구성 
  # - joinConfigurationL: 워커 노드가 클러스터에 조인될 때 사용되는 구성
  # --------------
  # kubeletExtraArgs: kubelet에 추가 인자를 전달 
  # - node-labels: "node.kubernetes.io/nfs-client=true"
  #   - 이 레이블은 NFS 클라이언트가 설치된 노드를 식별하는 데 사용됨
  #   - 노드가 NFS 클라이언트 역할을 할 수 있음을 나타냅니다. 이 라벨을 통해 특정 노드가 NFS 클라이언트로 작동하는지 확인할 수 있습니다.
  # --------------
  # node-labels: "ingress-ready=true"
  # - 노드가 Ingress 컨트롤러를 실행할 준비가 되었음을 나타냅니다. 
  # - Ingress 컨트롤러가 특정 라벨을 가진 노드에서만 실행되도록 제한하는데 유용합니다.
  # - 이게 없어서 그냥 ingress-nginx 컨트롤러만 설치했을 때 밑의 에러가 났구나
  #   - 0/4 nodes are available: 4 node(s) didn't match Pod's node affinity/selector. 
  #     preemption: 0/4 nodes are available: 
  #     4 Preemption is not helpful for scheduling
  # --------------
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.kubernetes.io/nfs-client=true"
        node-labels: "ingress-ready=true"
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.kubernetes.io/nfs-client=true"

- role: worker
  image: kindest/node:v1.30.2
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.kubernetes.io/nfs-client=true"
- role: worker
  image: kindest/node:v1.30.2
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.kubernetes.io/nfs-client=true"
- role: worker
  image: kindest/node:v1.30.2
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node.kubernetes.io/nfs-client=true"

networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "127.0.0.1"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6444
