# 마스터3 - 워커3개로 구성
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.25.16
- role: control-plane
  image: kindest/node:v1.25.16
- role: control-plane
  image: kindest/node:v1.25.16
- role: worker
  image: kindest/node:v1.25.16
- role: worker
  image: kindest/node:v1.25.16
- role: worker
  image: kindest/node:v1.25.16
