# https://github.com/banzaicloud/koperator 
# 주키퍼 오퍼레이터와 주키퍼 클러스터는 따로 설치해야 한다.
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
    name: zookeeper-server
    namespace: zookeeper
spec:
    replicas: 1
    persistence:
        reclaimPolicy: Delete