apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io # ‘Application’ 리소스를 삭제하면 관련된 쿠버네티스 리소스(파드 등)까지 같이 삭제하는 옵션
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc # ArgoCD가 설치된 쿠버네티스로 지정
  project: default
  source:
    helm:  # 애플리케이션 설치 형태를 헬름, 매니페스트 등을 지원
      valueFiles:
      - ../values-apply.yaml
    path: helm/nginx/nginx
    repoURL: https://github.com/ymmu/k8s_data_infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true