apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/k8s
    server: 192.168.45.48 # 다이나믹하게 넣고 싶은데 관리가 귀찮다. $(hostname -I | awk '{print $1}')
