apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        volumeMounts:
        - name: nfs
          mountPath: /mnt
        command: ["/usr/bin/tail", "-f", "/dev/null"]  # 컨테이너가 종료되지 않도록 함
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-pvc