apiVersion: batch/v1
kind: Job
metadata:
  name: normal-end
spec:
  completionMode: Indexed  # required for the feature
  # backoffLimitPerIndex: 1  # maximal number of failures per index
  # maxFailedIndexes: 5      # maximal number of failed indexes before terminating the Job execution
  # 위치가 이상하게 들어가 있었음;;
  completions: 6
  parallelism: 2
  ttlSecondsAfterFinished: 3 # job finished(either Complete or Failed) 후 100초 후에 삭제. 
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sh",  "-c", "sleep 5; exit 0"]
      restartPolicy: Never